version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./.env:/.env
    command: ["./main"]
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always